# Generated by Django 4.1 on 2023-03-15 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-datetime"]},
        ),
    ]
